apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  labels:
    app: hello-world
  annotations:
    # enforce https
#    kubernetes.io/ingress.allow-http: "false"
    #
    # client cert settings
#    ingress.kubernetes.io/force-ssl-redirect: "true"
    # Enable client certificate authentication
#    ingress.kubernetes.io/auth-tls-verify-client: "on"
    # Create the secret containing the trusted ca certificates with `kubectl create secret generic auth-tls-chain --from-file=ca.crt --namespace=default`
#    ingress.kubernetes.io/auth-tls-secret: "default/basicwebclient-trust"
    # Specify the verification depth in the client certificates chain
#    ingress.kubernetes.io/auth-tls-verify-depth: "3"
    # Specify an error page to be redirected to verification errors
#    # nginx.ingress.kubernetes.io/auth-tls-error-page: "http://www.mysite.com/error-cert.html"
    # Specify if certificates are passed to upstream server
#    ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
    ingress.bluemix.net/appid-auth: "bindSecret=binding-app-id-test namespace=default requestType=web serviceName=hello-service,hello-frontend-service"

  namespace: default
spec:
  rules:
  - host: foo1.bar.com
    http:
      paths:
      - path: /api
        backend:
          serviceName: hello-service
          servicePort: 8080
      - path: /hello
        backend:
          serviceName: hello-frontend-service
          servicePort: 8080
  tls:
  - secretName: foo1secret
    hosts:
    - foo1.bar.com

